FROM apache/airflow:2.7.1-python3.10

USER root
# Install git (needed for some pip packages)
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean

USER airflow

# Install your ML dependencies inside the Airflow container
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt